# Generated by Django 3.2.9 on 2023-06-14 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_room_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlottery',
            name='lottery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='mainapp.lottery', verbose_name='Розыгрыш'),
        ),
    ]
