# Generated by Django 3.2.9 on 2023-06-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_memberlottery_lottery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активная'),
        ),
    ]
