# Generated by Django 3.2.9 on 2023-06-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_room_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberlottery',
            name='session_key_user',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ключ сессии'),
        ),
    ]
