# Generated by Django 3.2.9 on 2023-06-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_memberlottery_session_key_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberlottery',
            name='win_money',
            field=models.PositiveIntegerField(default=0, verbose_name='Выиграл (руб.)'),
        ),
    ]
