# Generated by Django 3.2.9 on 2023-06-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_memberlottery_win_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlottery',
            name='num_member',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядковый номер участника'),
        ),
    ]
