# Generated by Django 3.2.9 on 2023-06-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_memberlottery_num_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlottery',
            name='token_user',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Токен пользователя'),
        ),
    ]
